# Generated by Django 4.2.30 on 2026-09-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.TextField()),
                ('player_name', models.TextField()),
                ('player_damage', models.IntegerField()),
                ('player_souls', models.IntegerField()),
                ('player_side', models.TextField()),
                ('player_chart', models.IntegerField()),
            ],
        ),
    ]
